### ISSUE TITLE
Эти библиотеки, на только С#

### ISSUE THREAD

**Issue by 3dpoint** [biletnikov/avr-nec-ir-decoder#2]
Здравствуйте. Отличные библиотеки. А нельзя ли этот проект посмотреть на простом С#.
Я начинающий. Делаю для себя проект на С# (Atmega48) "управление ламповым усилителем".
Хотел, с Вашего разрешения, использовать Ваш код в некоммерческих целях.
С уважением Владимир (3dpoint@mail.ru)

**Comment by biletnikov** [comment]
Здравствуйте, Владимир.
С# (Atmega48)     ?  Вы имеет ввиду C? Т.к. C# - это язык платформы .NET и он не используется для пограммирования микроконтроллеров. 
В можете скомпилировать библиотеку C компилятором (поменяв расширение файлов с cpp на c), должно скомпилироваться нормально, т.к. он не использует возможности C++ и по своей сути предстовляет собой C код.

**Comment by 3dpoint** [comment]
Спасибо Сергей за ответ, уже разбираюсь.
--
Отправлено из Mail.ru для Android суббота, 22 июня 2019г., 01:01 +03:00 от Sergei Biletnikov  notifications@github.com :

**Comment by biletnikov** [comment]
Если не получится скомпилировать - спрашивайте, помогу! А ещё интересно узнать о вашем проекте, что именно вы будете регулировать в ламповом усилителе ?

**Comment by 3dpoint** [comment]
Большое спасибо Сергей за предложение помощи. Вроде дело идет потихоньку. Стараюсь все таки сделать сам, что смогу. Если у меня будет большой «затык» обращусь к Вам.

С ув. Владимир

**Comment by 3dpoint** [comment]
Здравствуйте Сергей. Ну  вот как и обещал, случился "затык" :-)
На Атмега88 все четко работает. 
Пробую на Атмега48, ни как. Компилируется без ошибок, но ИК не принимает.
Работаю в AtmelStudio 7 и Proteus 8_6. Три дня ковырял даташит на Атмегу 48-88-168.
У 48 и 88 регистры и пр. совпадают (если я не ошибся) .
Думаю что  с таймером что то не так у меня, хотя проверял по даташиту - все вроде правильно.
Могу Вам скинуть полностью  проекты  Протеуса и АтмелСтудио или дать ссылку на папку с проектом в моём облаке Майл-ру. Или вот мой адрес 3dpoint-собака-mail.ru, можно через почту.
Я не знаю как правильно тут это обсудить, может тут правила есть какие.
Прошу помощи.
С  уважением Владимир.

**Comment by biletnikov** [comment]
Владимир, если на ATmega88 всё чётко работает, а на ATMega48 нет, то вероятно всего проблема в конфигурации - необходимо перепроверить фьюзы, убедится что МК работает на необходимой частоте. Убедится, что программа скомпилирована именно для ATmega48.  Эти МК отличаются лишь количеством флэш памяти. biletnikov-собака-gmail.com  Можете прислать проект.

**Comment by biletnikov** [comment]
Разобрались
